title: ./muscat.sh
name: George Muscat
email: george@muscat.sh
description: ""
baseurl: "" # leave this blank so the home button redirects to / instead of /6443
url: "https://muscat.sh/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: GeorgeMuscat

theme: minima
show_downloads: false
github:
  is_project_page: false
markup:
  goldmark:
    renderer:
      unsafe: true
minima:
  skin: dark
  social_links:
    github: GeorgeMuscat
    linkedin: george-muscat

header_pages:
  - home.md
